config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    resources :products
    resources :subcategories
    get 'lock' => 'pages#lock'
  end

  resources :subcategories do
    resources :products
    get 'lock' => 'pages#lock'
  end

  get 'contact' => 'pages#contact'

  root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, dependent: :destroy
  has_many :products

  accepts_nested_attributes_for :subcategories, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :products, :reject_if => :all_blank, :allow_destroy => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :subcategory
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  has_many :products
  
  accepts_nested_attributes_for :products, :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_sidebar
  
  def set_sidebar
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    #@subcategory = Subcategory.new
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params[:category].permit(:name, subcategories_attributes:[:id, :name, :_destroy])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home ; end

  def lock ; end

  def contact ; end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :find_category

  # GET /products
  # GET /products.json
  def index
    @products = @category.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = @category.products.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = @category.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to category_path(@category), notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to category_path(@category), notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to category_path(@category), notice: 'Product was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def find_category
      @category = Category.find(params[:category_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def comment; end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.slim
= simple_form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message  

  = f.input :name

  h3 subcategories
  #subcategories
    = f.simple_fields_for :subcategories do |subcategory|
      = render 'categories/partial/subcategory_fields', :f => subcategory
    .links
      = link_to_add_association 'add subcategory', f, :subcategories, :partial => 'categories/partial/subcategory_fields'

  = f.submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'DELETE', category_path(@category), method: :delete
'|
= link_to 'Back', categories_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/no_use/_form.html.slim
= simple_form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  = f.input :name
  .actions = f.submit

app/views/categories/no_use/index.html.slim
h1 Listing categories

table
  thead
    tr
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = link_to 'Show', category
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Category', new_category_path

app/views/categories/partial/_sample_product.html.slim
div.col-md-4.margin_bottom
  div.col-md-12#product_box
    = link_to category_product_path(@category, product) do
      h3.white_text_border style='text-decoration:none; color:#222;'
        strong = product.name
      = image_tag '71.jpg', width:'100%'
      p style='color:#222;' = product.description
      - link_to 'Show', category_product_path(@category, product)
      - link_to 'Edit', edit_category_product_path(@category, product)
      - link_to 'Destroy', category_product_path(@category, product), data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/categories/partial/_subcategory_fields.html.slim
.nested-fields
  = f.input :name
  = link_to_remove_association "remove", f

app/views/categories/show.html.slim
div.container-fluid#product_showcase_container

  p#notice = notice

  h1.white_text_border
    strong
      span.fa.fa-pagelines = @category.name

  hr style='background-color: limegreen; height: 3px; border: none;
box-shadow: 3px -3px 8px 2px rgba(255,255,255,1);'


  div.row
  - @category.products.each do |product|
    - 6.times do
      = render 'categories/partial/sample_product', product: product

  = link_to 'New Product', new_category_product_path(@category)

app/views/common/_sidebar.html.slim
div#category_list
  h3#category_text
    span.fa.fa-bars
    '  所有產品

  ul
    - if Category.exists?
      - @categories.each do |category|
        li
          - if category.name.include? "2014"
            = link_to category.name, category_lock_path(category)
            |  
            = content_tag(:span, '', class:"fa fa-lock")
          - else
            = link_to category.name, category_path(category)

          /|  
          /= content_tag(:span, '', class:"fa fa-caret-down") if category.subcategories.exists?
          /- if category.subcategories.exists?

            ul.margin_left
              - category.subcategories.each do |subcategory|
                li
                  - if subcategory.name.include? "2014"
                    = link_to subcategory.name, subcategory_lock_path(subcategory)
                    |  
                    = content_tag(:span, '', class:"fa fa-lock")
                  - else
                    a href='/categories/1'
                      = subcategory.name
                  /= link_to subcategory.name, category_subcategory_path(category, subcategory)
    li
      = link_to new_category_path do
        span.fa.fa-plus
        '   New

app/views/layouts/application.html.slim
doctype html
html
  head
    title ItaiDemo
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  meta name="viewport" content="width=device-width, initial-scale=1.0"

  body
    div.container-fluid.no_padding.bg_img
      / 如果需要置中的話，可使用col-md-offset
      div.col-md-10.row_1.white#top_bar.margin_left
        = link_to root_path do
          h1#brand
            span.fa.fa-tree
            /= image_tag 'favicon.ico', size:'40x40'
            '   義台人造

        p#notice = notice

      div.col-md-2.col-sm-3.white.sidebar.container-fluid.hidden-xs.no_padding.margin_left
        == render 'common/sidebar'
      div.col-sm-12.white.sidebar.container-fluid.visible-xs.no_padding
        == render 'common/sidebar'
      div.col-md-offset-3.col-md-8.col-sm-offset-3.col-sm-9#content_div.no_padding style="margin-top: 100px"
        == yield

app/views/pages/contact.html.erb
<div class="col-sm-offset-2 col-sm-8 white">
  <form class="form-horizontal well transparent" id="contact_form">
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">電子郵件</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">姓名</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">訊息</label>
      <div class="col-sm-10">
        <textarea class="form-control" rows="3"></textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-info btn-lg">送出</button>
      </div>
    </div>
  </form>
  <div class="text-center">
    <h3>公司地址: 臺中市清水區高美路371-4號</h3>
    <h3>訪客來廠.請先提前預約.</h3>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3636.5969783488636!2d120.5656465!3d24.2908035!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x34691373d22e736d%3A0x2816f762af3a57c!2sNo.+371-4%2C+Gaomei+Rd%2C+Qingshui+District%2C+Taichung+City%2C+436!5e0!3m2!1sen!2stw!4v1436973529738" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/pages/home.html.slim
  div.col-md-11.col-sm-11.no_padding style="background:rgba(255,255,153,1);"
    div.col-md-12.col-sm-12.row_10_height.no_padding
      = render 'pages/partial/photo_grid_2'

    div.col-md-12.col-sm-12.black.margin_bottom

      div.col-md-12.col-sm-12.row_4_height.padding_left2x.padding_right2x.padding_top2x
        div.col-md-12.col-sm-12.row_2.text-center.no_padding style='border-bottom: 2px solid green; padding-bottom: 10px;'
          = link_to category_path(1) do
            h3.black.pull-left.white_text_border
              strong
                span.fa.fa-pagelines
                |   大型聖誕樹
        div.col-md-4.col-sm-4.row_9.no_padding_left.padding_top.padding_right2x
          div.col-md-12.col-sm-12.row_12#product_img2
        div.col-md-4.col-sm-4.row_9.padding_top
          div.col-md-12.col-sm-12.row_12#product_img3
        div.col-md-4.col-sm-4.row_9.no_padding_right.padding_top.padding_left2x
          div.col-md-12.col-sm-12.row_12#product_img4

      div.col-md-12.col-sm-12.row_4_height.padding_left2x.padding_right2x.padding_top2x
        div.col-md-12.col-sm-12.row_2.text-center.no_padding style='border-bottom: 2px solid green; padding-bottom: 10px;'
          = link_to category_path(1) do
            h3.black.pull-left.white_text_border
              strong
                span.fa.fa-pagelines
                |   人造草皮
        div.col-md-4.col-sm-4.row_9.no_padding_left.padding_top.padding_right2x
          div.col-md-12.col-sm-12.row_12#product_img2
        div.col-md-4.col-sm-4.row_9.padding_top
          div.col-md-12.col-sm-12.row_12#product_img4
        div.col-md-4.col-sm-4.row_9.no_padding_right.padding_top.padding_left2x
          div.col-md-12.col-sm-12.row_12#product_img3

      div.col-md-12.col-sm-12.row_4_height.padding_left2x.padding_right2x.padding_top2x
        div.col-md-12.col-sm-12.row_2.text-center.no_padding style='border-bottom: 2px solid green; padding-bottom: 10px;'
          = link_to category_path(1) do
            h3.black.pull-left.white_text_border
              strong
                span.fa.fa-pagelines
                |   人造花材
        div.col-md-4.col-sm-4.row_9.no_padding_left.padding_top.padding_right2x
          div.col-md-12.col-sm-12.row_12#product_img3
        div.col-md-4.col-sm-4.row_9.padding_top
          div.col-md-12.col-sm-12.row_12#product_img2
        div.col-md-4.col-sm-4.row_9.no_padding_right.padding_top.padding_left2x
          div.col-md-12.col-sm-12.row_12#product_img4

app/views/pages/lock.html.slim
div.col-md-12.text-center.white.well.transparent
  h2 親愛的顧客您好，歡迎光臨義台人造。
  h2
    | 如您想了解此類商品，請先
    = link_to '聯繫我們', contact_path, id:'contact_link'
    | 。
  h3
    form.form-inline
      div.form-group
        label 請輸入密碼：
        input.form-control type='password'
      button.btn.btn-success type="submit" OK

    

app/views/pages/partial/_carousel_slide.html.slim
= content_tag :div, class:'row_12', data: { ride: "carousel" }, id: id do
  div.carousel-inner.row_12 role="listbox"
    div.item.row_12.active
      // 每張照片會包含一個連結作為圖片連結 
      div.row_12#item1 onclick="location.href='/categories/1/products/1';" style='background-image: url("#{image1}");'
      /= image_tag image1, class:'row_12'
      div.carousel-caption

    div.item.row_12
      div.row_12#item2 onclick="location.href='/categories/1/products/1';" style='background-image: url("#{image2}");'
      /= image_tag image2, class:'row_12'
      div.carousel-caption

css:
  #item1, #item2 {
    background-size: cover;
    background-position: center;
    cursor: pointer;
  }

app/views/pages/partial/_photo_grid_1.html.slim
div.col-md-4.row_12.no_padding.border_right    
  = render 'pages/partial/carousel_slide', image1: "product2_mini.jpg", image2: "fcc0_mini.jpg", id:'carousel_1'

div.col-md-5.row_6.no_padding.border_right.border_bottom    
  = render 'pages/partial/carousel_slide', image1: "8b46_mini.jpg", image2: "fcc0_mini.jpg", id:'carousel_2'

div.col-md-3.row_6.no_padding.border_bottom    
  = render 'pages/partial/carousel_slide', image1: "product2_mini.jpg", image2: "1bf5_mini.jpg", id:'carousel_3'

div.col-md-3.row_6.no_padding.border_right    
  = render 'pages/partial/carousel_slide', image1: "c4812_mini.jpg", image2: "fcc0_mini.jpg", id:'carousel_4'

div.col-md-5.row_6.no_padding
  = render 'pages/partial/carousel_slide', image1: "1bf5_mini.jpg", image2: "fcc0_mini.jpg", id:'carousel_5'

app/views/pages/partial/_photo_grid_2.html.slim
div.col-md-3.col-sm-3.row_4.no_padding
  = render 'pages/partial/carousel_slide', image1: "https://db.tt/n1Mfg6i0", image2: "https://db.tt/n1Mfg6i0", id:'carousel_1'

div.col-md-6.col-sm-6.row_4.no_padding
  = render 'pages/partial/carousel_slide', image1: "https://db.tt/HyUEWzvV", image2: "https://db.tt/WaMXXLKv", id:'carousel_2'

div.col-md-3.col-sm-3.row_4.no_padding
  = render 'pages/partial/carousel_slide', image1: "https://db.tt/dcVmXAj0", image2: "https://db.tt/Drt5732N", id:'carousel_3'

div.col-md-9.col-sm-9.row_8.no_padding
  div.col-md-8.col-sm-8.row_12.no_padding 
    = render 'pages/partial/carousel_slide', image1: "https://db.tt/KxnPPVmv", image2: "https://db.tt/Cu72bdry", id:'carousel_4'

  div.col-md-4.col-sm-4.row_6.no_padding
    = render 'pages/partial/carousel_slide', image1: "https://db.tt/Drt5732N", image2: "https://db.tt/HyUEWzvV", id:'carousel_5'

  div.col-md-4.col-sm-4.row_6.no_padding
    = render 'pages/partial/carousel_slide', image1: "https://db.tt/WaMXXLKv", image2: "https://db.tt/HyUEWzvV", id:'carousel_6'

div.col-md-3.col-sm-3.row_8.no_padding
  = render 'pages/partial/carousel_slide', image1: "https://db.tt/xboJFGkB", image2: "https://db.tt/Cu72bdry", id:'carousel_7'

app/views/products/_form.html.slim
= simple_form_for [@category, @product] do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.input :category_id, as: :select, collection: Category.all, selected: @category.id
  .field
    = f.input :name
  .field
    = f.input :description
  .actions = f.submit

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

= link_to 'Show', category_product_path(@category, @product)
'|
= link_to 'Back', category_products_path(@category)

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', category_products_path

app/views/products/no_use/index.html.slim
h1 Listing products

table
  thead
    tr
      th Name
      th Description
      th
      th
      th

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.description
        td = link_to 'Show', category_product_path(@category, product)
        td = link_to 'Edit', edit_category_product_path(@category, product)
        td = link_to 'Destroy', category_product_path(@category, product), data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product', new_category_product_path(@category)

app/views/products/partial/_product_related_products.html.slim
div.col-md-9.col-xs-8.row_4#product_related_products
  h4.white_text_border
    strong 相關商品
  hr
  // TODO: 用slice分兩行分別指定padding-right & left
  div.col-md-3
    = image_tag '123.jpg', width:'100%'
  div.col-md-3
    = image_tag 'c4812.jpg', width:'100%'
  div.col-md-3
    = image_tag '1bf5.jpg', width:'100%'
  div.col-md-3
    = image_tag 'fcc0.jpg', width:'100%'

app/views/products/partial/_product_showcase_description.html.slim
div.col-md-3.row_12#product_showcase_description
  div.col-md-12.col-xs-12.row_12
    strong.white_text_border.black
      span.fa.fa-pagelines
      = link_to @product.category.name, category_path(@product.category)
      span.fa.fa-angle-double-right
    h2.white_text_border
      strong = @product.name
    div.well.green.col-xs-12.black_shadow
      h4
        span.fa.fa-info
        '   商品特點
      hr.black_sm
      p Lorem ipsum dolor sit amet, consectetur adipiscing elit.apien viverra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
      /= @product.description
    = link_to '進一步了解', contact_path, class:'btn btn-primary btn-lg black_shadow white_text_border'
  /
    = link_to 'Edit', edit_category_product_path(@category, @product)
    '|
    = link_to 'Back', category_products_path

app/views/products/partial/_product_showcase_main_grid.html.slim
div.col-md-9.col-xs-12.row_9#product_showcase_main_grid
  div.col-md-12.row_7.hidden-xs.padding_bottom
    div.border.no_padding
      = image_tag '71.jpg', width:'100%'
  div.col-md-3.row_2.col-xs-12
    div.border.no_padding
      = image_tag '71.jpg', width:'100%'
  div.col-md-3.row_2.col-xs-12
    div.border.no_padding
      = image_tag '72.jpg', width:'100%'
  div.col-md-3.row_2.col-xs-12
    div.border.no_padding
      = image_tag '73.jpg', width:'100%'
  div.col-md-3.row_2.col-xs-12
    div.border.no_padding
      = image_tag '74.jpg', width:'100%'

app/views/products/show.html.slim
  div#product_showcase_container.row_12_height

    = render 'products/partial/product_showcase_main_grid'

    = render 'products/partial/product_showcase_description'

    = render 'products/partial/product_related_products'